### ISSUE TITLE
Better handling of ActiveRecord collections with JsonHelper

### ISSUE THREAD

**Issue by rkillackey** [LaunchPadLab/rails_util#20]
Opened by @wade00 

## Issue
When returning arrays of data, successful response sets type to a pluralized version of the class. So if I'm returning an array of blog posts, the `type` attribute will be `posts`. However, if the collection is an ActiveRecord collection instead of an array it will return `post/active_record_relation`.

## Solution
Change the way we're checking to see if a resource is multiple or single.
Current logic:
```ruby
return obj.class.to_s.underscore unless obj.is_a?(Array) && obj.count.positive?
obj.first.class.to_s.underscore.pluralize
```
Proposed logic:
```ruby
type = obj.try(:count) && obj.count.positive? ?
      obj.first.class.to_s.underscore.pluralize :
      obj.class.to_s.underscore
type.split('/')[0]
```

This handles both arrays and AR collections. Note that this doesn't handle an array of resources from multiple classes because it just pulls the first one. We may want to open another issue for that, though.

**Comment by rkillackey** [comment]
@dianacamacho If you haven't started on this, I have some availability today and I can take care of it!

**Comment by dianacamacho** [comment]
@rkillackey go for it!
