### ISSUE TITLE
Add ability to include additional data attribute in response with JsonHelper

### ISSUE THREAD

**Issue by rkillackey** [LaunchPadLab/rails_util#21]
Opened by @wade00 

## Issue
In Kubo we've found the need to include an `additional_data` param that doesn't fit cleanly in the `attributes` object. In our example it's a `total_count` of tasks.

## Solution
Add ability to pass in `additional_data` param with the resource.
In a controller:
```ruby
json_with tasks, additional_data: { total_task_count: total_task_count }
```

In JsonHelper:
```ruby
def serialize_json_resource(resource, **options)
  res = ActiveModelSerializers::SerializableResource.new(resource, options[:serializer_options] || {})
  serialized_obj = res.serializer_instance.object
  type = options[:resource] || set_serialized_object_type(serialized_obj)

  data = { type: type, attributes: res.serializer_instance }
  data[:additional_data] = options[:additional_data] if options && options[:additional_data]

  render json: { data: data }, **options
end
```

**Comment by rkillackey** [comment]
@wade00 Just to confirm, you'd like `additional_data` to be nested under `data`, instead of as a separate key? In the example given, is there any reason we couldn't add `total_count` to the resource serializer instead?

**Comment by wade00** [comment]
@rkillackey that's what worked well on Kubo, where we implemented it. I don't think it makes sense to add it to the resource because in my mind `total_count` is more akin to metadata about the collection rather than part of the resource itself.

I don't have a strong opinion on whether it's nested under the `data` key or not. Do things get tricky if you pair this with our requests library and set the `successDataPath` to something like `data.attributes`?

**Comment by rkillackey** [comment]
@wade00 Oh, got it! Yeah definitely doesn't make sense to add `total_count` to the serializer if it's referring to a collection of resources, d'oh.

It doesn't appear to be causing any issues to nest it this way, I was just confirming it made sense to do so. Though I think I agree with you, not sure it makes sense for `additional_data` to be nested on the same level as other options like `status`, etc.

**Comment by dianacamacho** [comment]
@rkillackey have you already implemented this? if not i have some time

**Comment by rkillackey** [comment]
@dianacamacho Go for it!
