### ISSUE TITLE
Add password validator

### ISSUE THREAD

**Issue by inveterateliterate** [LaunchPadLab/rails_util#27]
Consider adding the password validator to this package

**Comment by dpikt** [comment]
@inveterateliterate what's the background of this issue?

**Comment by inveterateliterate** [comment]
i added a password validator class in simply merit to meet adp requirements. Someone suggested it get added to these utils

**Comment by dpikt** [comment]
@inveterateliterate cool! Is it unique to adp or can it accept other password constraints?

**Comment by inveterateliterate** [comment]
currently written specific for adp requirements, but could abstract

**Comment by dpikt** [comment]
@inveterateliterate I'll add a ticket to the main repo for discussing how we want to handle password validations on the backend! Will probably involve abstracting one of these modules 👍

**Comment by rkillackey** [comment]
There are a few modules we've written to help with Rails validations in general, so the ticket doesn't have to be password specific
